// Block Types Definition — colors + procedural texture tile names (see textures.js)

export const BlockTypes = {
  AIR: {
    id: 0,
    name: 'Air',
    transparent: true,
    solid: false,
    color: 0x000000,
  },
  GRASS: {
    id: 1,
    name: 'Grass Block',
    transparent: false,
    solid: true,
    topColor: 0x5d9b3b,
    sideColor: 0x8b6b42,
    bottomColor: 0x8b6b42,
    textures: { top: 'grass_top', side: 'grass_side', bottom: 'dirt' },
  },
  DIRT: {
    id: 2,
    name: 'Dirt',
    transparent: false,
    solid: true,
    color: 0x8b6b42,
    texture: 'dirt',
  },
  STONE: {
    id: 3,
    name: 'Stone',
    transparent: false,
    solid: true,
    color: 0x808080,
    texture: 'stone',
  },
  COBBLESTONE: {
    id: 4,
    name: 'Cobblestone',
    transparent: false,
    solid: true,
    color: 0x707070,
    texture: 'cobble',
  },
  SAND: {
    id: 5,
    name: 'Sand',
    transparent: false,
    solid: true,
    color: 0xe8d8a8,
    texture: 'sand',
  },
  WOOD: {
    id: 6,
    name: 'Oak Log',
    transparent: false,
    solid: true,
    topColor: 0xc4a06a,
    sideColor: 0x8b5a2b,
    textures: { top: 'log_top', bottom: 'log_top', side: 'log_side' },
  },
  LEAVES: {
    id: 7,
    name: 'Oak Leaves',
    transparent: true,
    solid: false,
    color: 0x2e8b2e,
    texture: 'leaves',
  },
  PLANKS: {
    id: 8,
    name: 'Oak Planks',
    transparent: false,
    solid: true,
    color: 0xc49a6c,
    texture: 'planks',
  },
  GLASS: {
    id: 9,
    name: 'Glass',
    transparent: true,
    solid: true,
    color: 0x88ccff,
    opacity: 0.3,
    texture: 'glass',
  },
  BEDROCK: {
    id: 10,
    name: 'Bedrock',
    transparent: false,
    solid: true,
    color: 0x1a1a1a,
    unbreakable: true,
    texture: 'bedrock',
  },
  COAL_ORE: {
    id: 11,
    name: 'Coal Ore',
    transparent: false,
    solid: true,
    color: 0x7a7a7a,
    texture: 'coal_ore',
  },
  IRON_ORE: {
    id: 12,
    name: 'Iron Ore',
    transparent: false,
    solid: true,
    color: 0x7a7a7a,
    texture: 'iron_ore',
  },
  GOLD_ORE: {
    id: 13,
    name: 'Gold Ore',
    transparent: false,
    solid: true,
    color: 0x7a7a7a,
    texture: 'gold_ore',
  },
  DIAMOND_ORE: {
    id: 14,
    name: 'Diamond Ore',
    transparent: false,
    solid: true,
    color: 0x7a7a7a,
    texture: 'diamond_ore',
  },
  WATER: {
    id: 15,
    name: 'Water',
    transparent: true,
    solid: false,
    color: 0x4488dd,
    opacity: 0.4,
    liquid: true,
    texture: 'water',
  },
  SIGN: {
    id: 16,
    name: 'Sign',
    // Non-solid so players don't collide with an invisible full cube;
    // rendered only via SignManager custom mesh (no chunk cube frame).
    transparent: true,
    solid: false,
    color: 0xb8956a,
    texture: 'sign',
    isSign: true,
  },
  TORCH: {
    id: 17,
    name: 'Torch',
    transparent: true,
    solid: false,
    color: 0xffaa33,
    texture: 'torch',
    isTorch: true,
    light: true,
  },
  SAPLING: {
    id: 18,
    name: 'Oak Sapling',
    transparent: true,
    solid: false,
    color: 0x3d8b37,
    texture: 'leaves',
    isSapling: true,
  },
  CHEST: {
    id: 19,
    name: 'Chest',
    transparent: false,
    solid: true,
    color: 0x8b5a2b,
    texture: 'chest',
    isChest: true,
  },
  BED: {
    id: 20,
    name: 'Bed',
    transparent: false,
    solid: true,
    color: 0xc04050,
    texture: 'bed',
    isBed: true,
  },
  CODE_BLOCK: {
    id: 21,
    name: 'Code Block',
    transparent: false,
    solid: true,
    color: 0x2a2a40,
    // Per-face labels drawn as separate atlas tiles
    faceTextures: {
      '+x': 'code_px',
      '-x': 'code_nx',
      '+y': 'code_py',
      '-y': 'code_ny',
      '+z': 'code_pz',
      '-z': 'code_nz',
    },
    texture: 'code_px',
    isCodeBlock: true,
  },
  LED: {
    id: 22,
    name: 'LED Block',
    transparent: false,
    solid: true,
    color: 0xff2020,
    texture: 'led',
    isLed: true,
    light: true,
  },
  MARS_PORTAL: {
    id: 23,
    name: 'Mars Portal',
    transparent: true,
    solid: true,
    color: 0xc45a2c,
    texture: 'mars_portal',
    isPortal: true,
    portalTarget: 'mars',
  },
  EARTH_PORTAL: {
    id: 24,
    name: 'Earth Portal',
    transparent: true,
    solid: true,
    color: 0x3d8bfd,
    texture: 'earth_portal',
    isPortal: true,
    portalTarget: 'earth',
  },
  MARS_ROCK: {
    id: 25,
    name: 'Mars Rock',
    transparent: false,
    solid: true,
    color: 0xa85a3a,
    texture: 'mars_rock',
  },
  MARS_DUST: {
    id: 26,
    name: 'Mars Dust',
    transparent: false,
    solid: true,
    color: 0xc47a4a,
    texture: 'mars_dust',
  },
  MARS_ICE: {
    id: 27,
    name: 'Mars Ice',
    transparent: true,
    solid: true,
    color: 0xc8e8f8,
    texture: 'mars_ice',
  },
  MARS_BASALT: {
    id: 28,
    name: 'Mars Basalt',
    transparent: false,
    solid: true,
    color: 0x3a2a28,
    texture: 'mars_basalt',
  },
  MARS_CRYSTAL: {
    id: 29,
    name: 'Mars Crystal',
    transparent: true,
    solid: true,
    color: 0xb44cff,
    texture: 'mars_crystal',
    light: true,
  },
  MARS_METEORITE: {
    id: 30,
    name: 'Meteorite',
    transparent: false,
    solid: true,
    color: 0x2a2a32,
    texture: 'mars_meteorite',
  },
  MARS_MAGMA: {
    id: 31,
    name: 'Mars Magma',
    transparent: true,
    solid: false,
    liquid: true,
    color: 0xff5520,
    opacity: 0.85,
    texture: 'mars_magma',
    light: true,
  },
  MARS_BRICK: {
    id: 32,
    name: 'Mars Brick',
    transparent: false,
    solid: true,
    color: 0x8b4030,
    texture: 'mars_brick',
  },
  RUST_ORE: {
    id: 33,
    name: 'Rust Ore',
    transparent: false,
    solid: true,
    color: 0x8b4510,
    texture: 'rust_ore',
  },
  ALIEN_FUNGUS: {
    id: 34,
    name: 'Alien Fungus',
    transparent: true,
    solid: false,
    color: 0x66ff99,
    texture: 'alien_fungus',
    isPlant: true,
    isFlower: true, // crossed plant mesh (not a full cube)
  },
  ANACHARIS: {
    id: 35,
    name: 'Anacharis',
    transparent: true,
    solid: false,
    color: 0x2d8b3e,
    texture: 'anacharis',
    isPlant: true,
    isAnacharis: true,
  },
  COOKED_ANACHARIS: {
    id: 36,
    name: 'Cooked Anacharis',
    transparent: true,
    solid: false,
    color: 0x6b8e23,
    texture: 'cooked_anacharis',
    isFood: true,
    foodHeal: 2,
  },
  FURNACE: {
    id: 37,
    name: 'Furnace',
    transparent: false,
    solid: true,
    color: 0x555555,
    texture: 'furnace',
    isFurnace: true,
  },
  IRON_INGOT: {
    id: 38,
    name: 'Iron Ingot',
    transparent: false,
    solid: true,
    color: 0xc0c0c8,
    texture: 'iron_ingot',
  },
  GOLD_INGOT: {
    id: 39,
    name: 'Gold Ingot',
    transparent: false,
    solid: true,
    color: 0xffd700,
    texture: 'gold_ingot',
  },
  COAL: {
    id: 40,
    name: 'Coal',
    transparent: false,
    solid: true,
    color: 0x1a1a1a,
    texture: 'coal',
  },
  WHEAT: {
    id: 41,
    name: 'Wheat',
    transparent: true,
    solid: false,
    color: 0xd4b84a,
    texture: 'wheat',
    isPlant: true,
    isWheat: true,
  },
  PRETZEL: {
    id: 42,
    name: 'Pretzel',
    transparent: true,
    solid: false,
    color: 0xc48a3a,
    texture: 'pretzel',
    isFood: true,
    foodHeal: 3,
  },
  POPPY: {
    id: 43,
    name: 'Poppy',
    transparent: true,
    solid: false,
    color: 0xe02030,
    texture: 'poppy',
    isPlant: true,
    isFlower: true,
  },
  DANDELION: {
    id: 44,
    name: 'Dandelion',
    transparent: true,
    solid: false,
    color: 0xffe040,
    texture: 'dandelion',
    isPlant: true,
    isFlower: true,
  },
  BLUE_ORCHID: {
    id: 45,
    name: 'Blue Orchid',
    transparent: true,
    solid: false,
    color: 0x4090ff,
    texture: 'blue_orchid',
    isPlant: true,
    isFlower: true,
  },
  PINK_TULIP: {
    id: 46,
    name: 'Pink Tulip',
    transparent: true,
    solid: false,
    color: 0xff80b0,
    texture: 'pink_tulip',
    isPlant: true,
    isFlower: true,
  },
  /** Oversized Mars carnivores — sticky, slow + drain hearts/cheese when entered */
  VENUS_FLYTRAP: {
    id: 47,
    name: 'Venus Flytrap',
    transparent: true,
    solid: false,
    color: 0x2d8b3e,
    texture: 'venus_flytrap',
    isPlant: true,
    isFlower: true,
    isCarnivorousPlant: true,
    plantHeight: 2.6,
    plantWidth: 1.55,
    stickyRadius: 0.95,
    stickyHeight: 2.4,
  },
  SUNDEW_ROUND: {
    id: 48,
    name: 'Round Sundew',
    transparent: true,
    solid: false,
    color: 0xd45a8a,
    texture: 'sundew_round',
    isPlant: true,
    isFlower: true,
    isCarnivorousPlant: true,
    plantHeight: 2.2,
    plantWidth: 1.7,
    stickyRadius: 1.05,
    stickyHeight: 2.0,
  },
  SUNDEW_THREAD: {
    id: 49,
    name: 'Thread Sundew',
    transparent: true,
    solid: false,
    color: 0xe878a0,
    texture: 'sundew_thread',
    isPlant: true,
    isFlower: true,
    isCarnivorousPlant: true,
    plantHeight: 2.9,
    plantWidth: 1.35,
    stickyRadius: 0.85,
    stickyHeight: 2.7,
  },
  SUNDEW_CAPE: {
    id: 50,
    name: 'Cape Sundew',
    transparent: true,
    solid: false,
    color: 0xc04070,
    texture: 'sundew_cape',
    isPlant: true,
    isFlower: true,
    isCarnivorousPlant: true,
    plantHeight: 2.5,
    plantWidth: 1.5,
    stickyRadius: 0.95,
    stickyHeight: 2.3,
  },
  PITCHER_PLANT: {
    id: 51,
    name: 'Pitcher Plant',
    transparent: true,
    solid: false,
    color: 0xb85a30,
    texture: 'pitcher_plant',
    isPlant: true,
    isFlower: true,
    isCarnivorousPlant: true,
    plantHeight: 3.1,
    plantWidth: 1.45,
    stickyRadius: 0.9,
    stickyHeight: 2.9,
  },
  HELIAMPHORA: {
    id: 52,
    name: 'Marsh Pitcher',
    transparent: true,
    solid: false,
    color: 0xd4a060,
    texture: 'heliamphora',
    isPlant: true,
    isFlower: true,
    isCarnivorousPlant: true,
    plantHeight: 2.8,
    plantWidth: 1.4,
    stickyRadius: 0.9,
    stickyHeight: 2.6,
  },
};

export const BlockIdToType = Object.fromEntries(
  Object.entries(BlockTypes).map(([key, val]) => [val.id, key])
);

export function getBlockType(id) {
  return BlockTypes[BlockIdToType[id]] || BlockTypes.AIR;
}

export function isSolid(blockType) {
  return blockType && blockType.solid;
}

export function isTransparent(blockType) {
  return blockType && blockType.transparent;
}

export function getBlockKeyById(id) {
  return BlockIdToType[id] || 'AIR';
}
